#!/bin/bash

bold=$(tput bold)
reset=$(tput sgr0)
rm -rf cloudflare-warp_*
echo ""
echo "${bold}Package details for debian:${reset}"
echo ""
curl -s https://pkg.cloudflareclient.com/dists/bookworm/main/binary-amd64/Packages
package_info=$(curl -s https://pkg.cloudflareclient.com/dists/bookworm/main/binary-amd64/Packages)
path=$(echo "$package_info" | grep -E "^Filename:" | awk '{print $2}')

echo "${bold}Downloading .deb file...${reset}"
echo ""
wget -q -nc --show-progress https://pkg.cloudflareclient.com/$path
ar x cloudflare-warp_*
tar -xvf data.tar.gz
echo ""
sudo systemctl stop warp-svc
dir=$(pwd)
sudo cp $dir/bin/warp-cli /bin/
sudo cp $dir/bin/warp-svc /bin/
sudo cp $dir/bin/warp-diag /bin/


echo ""
echo "${bold}Creating this .service file...${reset}"
echo ""
sudo rm -f /etc/systemd/system/warp-svc.service
sudo touch /etc/systemd/system/warp-svc.service
echo -e "[Unit]\nDescription=Cloudflare Warp Client Daemon\nAfter=pre-network.target\n\n[Service]\nType=simple\nExecStart=/bin/warp-svc\nDynamicUser=no\nCapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_SYS_PTRACE\nAmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_SYS_PTRACE\nRestart=always\n\n[Install]\nWantedBy=multi-user.target" | sudo tee /etc/systemd/system/warp-svc.service
sudo systemctl enable warp-svc
sudo systemctl start warp-svc


echo ""
echo "${bold}Waiting for few seconds for the services...${reset}"
echo ""
sleep 3
warp-cli registration delete

echo ""
echo "${bold}Registering WARP...${reset}"
echo ""
warp-cli registeration new
read -r -p "Do you want to connect to warp now? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    warp-cli connect
fi
rm -rf cloudflare-warp_* control.tar.gz data.tar.gz etc/ lib/ usr/ bin/ debian-binary
